Components
osallak/SpinShot pull request #12
Opened 2023-07-21 16:53 UTC by ataji

2023-07-21 19:12 UTC, lalouli requested changes
add ui directory

2023-07-21 19:16 UTC, ataji commented
ui directory is added

2023-07-21 19:52 UTC, FRAGG33R requested changes
create interfaces
add a good file structure

2023-07-22 10:33 UTC, lalouli approved these changes

2023-07-22 12:23 UTC, closed without merging