Feat/profile settings
osallak/SpinShot pull request #39
Opened 2023-08-18 14:11 UTC by osallak

run it and navigate /api route to get api docs

2023-08-18 15:01 UTC, Navoos requested changes
great work, but:
- You should use catch more often, but only on the top level so you don't have to use it in every await
-  You should avoid abusing any, like for example the type of req: Request insead of any

2023-08-18 21:26 UTC, kmlFaouzi approved these changes

2023-08-18 21:27 UTC, kmlFaouzi commented
excellent work,  keep up

2023-08-19 09:20 UTC, Navoos approved these changes
great job, keep the good work

2023-08-19 09:20 UTC, merged